### PR TITLE
Add kmod tcmu

### PR DESCRIPTION
**Pull request by Arau**

### CODE REVIEW

**Comment by Arau** [comment]
This PR is not ready to merge at there is a case scenario not implemented yet. 
When TCMU is not there, the script shouldn't fail.

**Comment by croomes** [comment]
README should be updated too?

**Comment by Arau** [comment]
> README should be updated too?

Yes, adding the changes into the README

**Review by croomes — APPROVED** [review]
Tested and appears to work.  Unsure about the colourised logging but can leave for now.

**Pull request merged**
